from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field


class ReportJsonSection(BaseModel):
    """Frontend-ready report section generated by the report writer."""

    section_key: str
    title: str
    summary: str
    bullets: list[str] = Field(default_factory=list)
    citation_ids: list[str] = Field(default_factory=list)
    chart_ids: list[str] = Field(default_factory=list)
    table_ids: list[str] = Field(default_factory=list)


class InvestmentPointJson(BaseModel):
    """One investment point with explicit source lineage."""

    title: str
    thesis: str
    supporting_metrics: list[str] = Field(default_factory=list)
    citation_ids: list[str] = Field(default_factory=list)


class RiskJson(BaseModel):
    """One risk item with citation lineage."""

    title: str
    description: str
    severity: str
    citation_ids: list[str] = Field(default_factory=list)


class FrontendReportJson(BaseModel):
    """Full JSON report payload designed for frontend rendering."""

    title: str
    company: str
    ticker: str
    market: str
    as_of_date: str
    report_type: str
    investment_summary: list[str] = Field(default_factory=list)
    key_issues: list[str] = Field(default_factory=list)
    financial_snapshot: dict[str, Any] = Field(default_factory=dict)
    investment_points: list[InvestmentPointJson] = Field(default_factory=list)
    earnings_outlook: ReportJsonSection
    valuation: ReportJsonSection
    risks: list[RiskJson] = Field(default_factory=list)
    conclusion: ReportJsonSection
    evidence_notes: list[str] = Field(default_factory=list)
    chart_ids: list[str] = Field(default_factory=list)
    table_ids: list[str] = Field(default_factory=list)
