from __future__ import annotations

from typing import Any, Literal, Optional

from pydantic import Field

from ai_research_department.models.base import TimestampedModel, new_id


class ChartArtifact(TimestampedModel):
    """Chart-ready data generated by the data department."""

    chart_id: str = Field(default_factory=lambda: new_id("CHART"))
    title: str
    chart_type: Literal["bar", "line", "scatter", "table_like"] = "bar"
    x_key: str = "metric"
    y_key: str = "value"
    data: list[dict[str, Any]] = Field(default_factory=list)
    evidence_ids: list[str] = Field(default_factory=list)
    estimate_ids: list[str] = Field(default_factory=list)
    image_path: Optional[str] = None
    description: Optional[str] = None


class TableArtifact(TimestampedModel):
    """Tabular data generated by the data department."""

    table_id: str = Field(default_factory=lambda: new_id("TABLE"))
    title: str
    columns: list[str] = Field(default_factory=list)
    rows: list[dict[str, Any]] = Field(default_factory=list)
    evidence_ids: list[str] = Field(default_factory=list)
    estimate_ids: list[str] = Field(default_factory=list)
    description: Optional[str] = None
